Hw 1
Fedich09/multithreading pull request #1
Opened 2021-02-22 16:26 UTC by Fedich09

2021-02-22 16:49 UTC, NikolayFatkullin approved these changes

2021-02-23 07:30 UTC, Sofasmile requested changes

2021-02-23 07:30 UTC, Sofasmile commented on src/main/java/Counter.java
> +    public int incAndGet() {
```suggestion
    public int increment() {
```

2021-02-23 07:30 UTC, Sofasmile commented on src/main/java/Counter.java
> +        return this.value;
```suggestion
        return ++value;
```

2021-02-23 07:30 UTC, Sofasmile commented on src/main/java/MyRunnable.java
> +        for (int i = 0; i < LIMIT; i++) {
```suggestion
        while (counter.get() < LIMIT) {
```

2021-02-23 09:51 UTC, Sofasmile approved these changes

2021-02-23 14:35 UTC, merged